const dataSong = [
  {
    id: 1,
    name: "chill-1",
    src: "https://audio.jukehost.co.uk/60OfP7vXyw1TveSMMlFuqmzjHLDPFH1B",
    list: "chill",
  },
  {
    id: 2,
    name: "chill-2",
    src: "https://audio.jukehost.co.uk/aPH2zhLYSpynGLX2suD5k8WI5Sv4iY02",
    list: "chill",
  },
  {
    id: 3,
    name: "chill-3",
    src: "https://audio.jukehost.co.uk/L8EGgqDpoIXjZEP4cauZbLhbvB7XGGVa",
    list: "chill",
  },
  {
    id: 4,
    name: "chill-4",
    src: "https://audio.jukehost.co.uk/z14H88loHeIYa6owbaivpBDiuNJNMnT9",
    list: "chill",
  },
  {
    id: 5,
    name: "chill-5",
    src: "https://audio.jukehost.co.uk/GO4UrkImCBHcYSpmWhaSv5UY9edFtXTA",
    list: "",
  },
  {
    id: 6,
    name: "chill-6",
    src: "https://audio.jukehost.co.uk/nmr5a6bEFxfhX74oxVYAbHuRxJZhTzut",
    list: "chill",
  },
  {
    id: 10,
    name: "chill-10",
    src: "https://audio.jukehost.co.uk/EyJd04azWg3c1X22Ow2i9Qv9YwiVLwBO",
    list: "chill",
  },
  {
    id: 7,
    name: "chill-7",
    src: "https://audio.jukehost.co.uk/abgkqrcnsFjTVSeYZQyfFzPb073ycDGz",
    list: "chill",
  },
  {
    id: 8,
    name: "chill-8",
    src: "https://audio.jukehost.co.uk/gNPaIEyVmsVlYI5BPa0xepNp81f3EOy3",
    list: "chill",
  },
  {
    id: 9,
    name: "chill-9",
    src: "https://audio.jukehost.co.uk/XKFvpCd9p2ONPDDPjLrIpECCbILUhiWM",
    list: "chill-9",
  },
  {
    id: 11,
    name: "focus-1",
    src: "https://audio.jukehost.co.uk/8uv5dqLU0n7CWPMbm78pOi7yszuZHebV",
    list: "focus",
  },
  {
    id: 12,
    name: "focus-2",
    src: "https://audio.jukehost.co.uk/h8xBUDhXDEj286E4j101DfbXH1uV2IJz",
    list: "focus",
  },
  {
    id: 13,
    name: "focus-3",
    src: "https://audio.jukehost.co.uk/Kj2PVglegtxbbCap7gY2lCdhJk7XBUGM",
    list: "focus",
  },
  {
    id: 14,
    name: "focus-4",
    src: "https://audio.jukehost.co.uk/jba918aEj6hBBRzquzqxy5usaBnsCnYn",
    list: "focus",
  },
  {
    id: 15,
    name: "focus-5",
    src: "https://audio.jukehost.co.uk/kVQ7nL6smn6iV2uwxwcdSGpxw0XwBdn8",
    list: "focus",
  },
  {
    id: 16,
    name: "focus-6",
    src: "https://audio.jukehost.co.uk/u7uwif0bascCjRkKyAS3nBvrM32ZAuQa",
    list: "focus",
  },
  {
    id: 17,
    name: "focus-7",
    src: "https://audio.jukehost.co.uk/u73O0osvsjGvVnp4b25iqshlzG3QFEmS",
    list: "focus",
  },
  {
    id: 18,
    name: "focus-8",
    src: "https://audio.jukehost.co.uk/wnXOAWdXVTS0eZpoOgn05BH2pUoQRRtz",
    list: "focus",
  },
  {
    id: 19,
    name: "focus-9",
    src: "https://audio.jukehost.co.uk/8H1RwWcnl3Ji8Teu6c9GHGMi3mWsWTFS",
    list: "focus",
  },
  {
    id: 20,
    name: "focus-10",
    src: "https://audio.jukehost.co.uk/sd5BUYaLXEqbN0luEba649wIuqgRHk17",
    list: "focus",
  },
  {
    id: 21,
    name: "sleepy-1",
    src: "https://audio.jukehost.co.uk/Qe5kdNYWmEpkVhvaN6eJFECEIT91wNgy",
    list: "sleepy",
  },
  {
    id: 22,
    name: "sleepy-2",
    src: "https://audio.jukehost.co.uk/sKs5atTpJ1kBegM4kKbXlpeubdf3beIW",
    list: "sleepy",
  },
  {
    id: 23,
    name: "sleepy-3",
    src: "https://audio.jukehost.co.uk/vYMjJlEXiTvo07I3RwRpPdHXQ6gUjXRa",
    list: "sleepy",
  },
  {
    id: 24,
    name: "sleepy-4",
    src: "https://audio.jukehost.co.uk/2vY1mmG28yVipEDeouErqUsy5Q7L6jq3",
    list: "sleepy",
  },
  {
    id: 25,
    name: "sleepy-5",
    src: "https://audio.jukehost.co.uk/cMmjoIlgVuhylMbAfdiA6SkZPQtwMlhU",
    list: "sleepy",
  },
  {
    id: 26,
    name: "sleepy-6",
    src: "https://audio.jukehost.co.uk/RmJbZNKIkQJybGHanhB4wdDfkbORuGfK",
    list: "sleepy",
  },
  {
    id: 27,
    name: "sleepy-7",
    src: "https://audio.jukehost.co.uk/YGp3PkoTdqPmFNe5onhgf1asjR2ZXWXD",
    list: "sleepy",
  },
  {
    id: 28,
    name: "sleepy-8",
    src: "https://audio.jukehost.co.uk/cVyhyQN7h5e2uTDijYi4JoLYyJX03apc",
    list: "sleepy",
  },
  {
    id: 29,
    name: "sleepy-9",
    src: "https://audio.jukehost.co.uk/8cri930SGODyQMmfqVzjrUCzVJ1803aj",
    list: "sleepy",
  },
  {
    id: 30,
    name: "sleepy-10",
    src: "https://audio.jukehost.co.uk/EQIVu7uiYQi3c3vElGhd0nBQ0RoneE7D",
    list: "sleepy",
  },
];

export default dataSong;
