import type { Metadata } from "next";
import "./globals.css";
import StatusGroup from "@/components/acction-elements/status-group";
import "react-tooltip/dist/react-tooltip.css";
import MenuGroup from "@/components/acction-elements/menu-group";
import ToogleTheme from "@/components/acction-elements/toogle-theme";
import YtbScreen from "@/components/acction-elements/ytb-screen";
import { Toaster } from "react-hot-toast";
import Promodo from "@/components/acction-elements/promodo";
import Tasks from "@/components/acction-elements/tasks";
import ManegeAudio from "@/components/acction-elements/manege-audio";
import { AudioProvider } from "@/contexts/audio-context";
import ReactH5AudioPlayer from "@/components/acction-elements/react-h5-audio-player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          suppressHydrationWarning
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          suppressHydrationWarning
        />
        <link
          suppressHydrationWarning
          href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body
        className={
          " m-plus-rounded-1c-regular flex min-h-screen flex-col items-center justify-between bg-white relative overflow-hidden"
        }
      >
        <AudioProvider>
          <>
            <StatusGroup />
            {children}
            <MenuGroup />
            {/* <ToogleTheme /> */}
            <YtbScreen />
            <Promodo />
            <Tasks />
            <ReactH5AudioPlayer />
            <Toaster position="bottom-right" reverseOrder={false} />
          </>
        </AudioProvider>
      </body>
    </html>
  );
}
